os:
 - linux
language: go
go:
 - 1.6
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libsystemd-dev
install:
 - mkdir -p $HOME/gopath/src/k8s.io
 - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/node-problem-detector
 - cd $HOME/gopath/src/k8s.io/node-problem-detector
script:
 - go test -v -race ./pkg/...
 - go build -race
